apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksdemo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: aksdemo
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: aksdemo
    spec:
      containers:
        - name: aksdemo
          image: pbaksdemo.azurecr.io/prasadbhalerao/demo
      imagePullSecrets: null
      – name: pb-docker-creds
