apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksdemo-deployment
  labels:
    app: aksdemo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aksdemo
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: aksdemo
    spec:
      containers:
        - name: aksdemo
          image: pbaksdemo.azurecr.io/prasadbhalerao/demo:v1
          ports:
            - containerPort: 3000
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_server
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db_username
      imagePullSecrets:
        - name: pb-docker-creds
