apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksdemo-deployment
  labels:
    app: aksdemo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aksdemo
  template:
    metadata:
      labels:
        app: aksdemo
    spec:
      containers:
      - name: aksdemo
        image: pbaksdemo.azurecr.io/prasadbhalerao/demo
        ports:
        - containerPort: 3000
        envFrom:
          configMapRef:
            name: app-config
        env:
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD 
      imagePullSecrets:
      - name: pb-docker-creds